@startuml
title
    Keyple - keyple-card-generic-java-lib - 3.0.+ (2023-10-04)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External API references__ :
    ** <color:blue><back:yellow>**keypop-reader-java-api**</back>
    ** <back:cyan>**keyple-common-java-api**</back>
    ** <back:orange>**keyple-service-resource-java-lib**</back>
end legend

package "org.eclipse.keyple.card.generic" as generic {
    +class "<<<back:cyan>KeypleCardExtension</back>>>\n**final** GenericExtensionService" as GenericExtensionService <<green>> {
        --
        +{static} GenericExtensionService getInstance ()

        +<color:blue>GenericCardSelectionExtension createGenericCardSelectionExtension ()
        +<back:orange>CardResourceProfileExtension</back> createCardResourceProfileExtension (<color:blue><back:yellow>CardSelector<IsoCardSelector> cardSelector</back></color>, GenericCardSelectionExtension genericCardSelectionExtension)
        +CardTransactionManager createCardTransaction (<back:yellow>CardReader</back> cardReader, <back:yellow>SmartCard</back> card)

        -- **KeypleCardExtension** --
        +String getCommonApiVersion ()
        +String getReaderApiVersion ()
        +String getCardApiVersion ()
    }
    +interface "<color:blue><<<back:yellow>CardSelectionExtension</back>>>\n<color:blue>GenericCardSelectionExtension" as GenericCardSelectionExtension {
        +<color:red>GenericCardSelection filterByCardProtocol (String cardProtocol)

        +<color:red>GenericCardSelection filterByPowerOnData (String powerOnDataRegex)

        +<color:red>GenericCardSelection filterByDfName (byte[] aid)
        +<color:red>GenericCardSelection filterByDfName (String aid)
        +<color:red>GenericCardSelection setFileOccurrence (FileOccurrence fileOccurrence)
        +<color:red>GenericCardSelection setFileControlInformation (FileControlInformation fileControlInformation)
        +GenericCardSelectionExtension addSuccessfulStatusWord (int statusWord)
    }
    +enum "<color:red>FileOccurrence" as FileOccurrence <<green>> {
        <color:red>FIRST
        <color:red>LAST
        <color:red>NEXT
        <color:red>PREVIOUS
    }
    +enum "<color:red>FileControlInformation" as FileControlInformation <<green>> {
        <color:red>FCI
        <color:red>FCP
        <color:red>FMD
        <color:red>NO_RESPONSE
    }
    +interface CardTransactionManager {
        +CardTransactionManager prepareApdu (String apduCommand)
        +CardTransactionManager prepareApdu (byte[] apduCommand)
        +CardTransactionManager prepareApdu (byte cla, byte ins, byte p1, byte p2, byte[] dataIn, Byte le)

        +<color:red>CardTransactionManager prepareReleaseChannel ()

        +List<byte[]> processApdusToByteArrays (<color:blue>ChannelControl channelControl</color>) throws TransactionException
        +List<String> processApdusToHexStrings (<color:blue>ChannelControl channelControl</color>) throws TransactionException
    }
    +enum "<color:blue>ChannelControl" as ChannelControl <<green>> {
        <color:blue>KEEP_OPEN
        <color:blue>CLOSE_AFTER
    }
    +class "<<RuntimeException>>\n**final** TransactionException" as TransactionException {
        +TransactionException (String message)
        +TransactionException (String message, Throwable cause)
    }
}

' Associations

' == LAYOUT ==

GenericExtensionService ..> GenericCardSelectionExtension #C_LINK : create >
GenericExtensionService ..> CardTransactionManager #C_LINK : create >

GenericCardSelectionExtension +-- FileOccurrence
GenericCardSelectionExtension ..> FileOccurrence #C_USE : use >
GenericCardSelectionExtension +-- FileControlInformation
GenericCardSelectionExtension ..> FileControlInformation #C_USE : use >

CardTransactionManager ..> ChannelControl #C_USE : use >
CardTransactionManager ..> TransactionException #C_THROW : throw >

' == STYLE ==

package generic #C_GREY1 {}


@enduml