@startuml
title
    Keyple - keyple-card-generic-java-lib - 3.2.+ (2025-11-10)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External API references__ :
    ** <back:yellow>**keypop-reader-java-api**</back>
    ** <back:cyan>**keyple-common-java-api**</back>
    ** <back:orange>**keyple-service-resource-java-lib**</back>
end legend

package "org.eclipse.keyple.card.generic" as generic {
    +class "<<<back:cyan>KeypleCardExtension</back>>>\n**final** GenericExtensionService" as GenericExtensionService <<green>> {
        --
        +{static} GenericExtensionService getInstance ()

        +GenericCardSelectionExtension createGenericCardSelectionExtension ()
        +<back:orange>CardResourceProfileExtension</back> createCardResourceProfileExtension (<back:yellow>IsoCardSelector cardSelector</back>, GenericCardSelectionExtension genericCardSelectionExtension)
        +CardTransactionManager createCardTransaction (<back:yellow>CardReader</back> cardReader, <back:yellow>SmartCard</back> card)

        -- **KeypleCardExtension** --
        +String getCommonApiVersion ()
        +String getReaderApiVersion ()
        +String getCardApiVersion ()
    }
    +interface "<<<back:yellow>CardSelectionExtension</back>>>\nGenericCardSelectionExtension" as GenericCardSelectionExtension {
        +GenericCardSelectionExtension addSuccessfulStatusWord (int statusWord)
    }
    +interface "<color:blue><<<back:yellow>CardTransactionManager</back>>></color>\nCardTransactionManager" as CardTransactionManager {
        +CardTransactionManager prepareApdu (String apduCommand)
        +CardTransactionManager prepareApdu (byte[] apduCommand)
        +CardTransactionManager prepareApdu (byte cla, byte ins, byte p1, byte p2, byte[] dataIn, Byte le)

        +<color:red><s>List<byte[]> processApdusToByteArrays (ChannelControl channelControl) throws TransactionException
        +<color:red><s>List<String> processApdusToHexStrings (ChannelControl channelControl) throws TransactionException

        +<color:blue>List<byte[]> getResponsesAsByteArrays ()
        +<color:blue>List<String> getResponsesAsHexStrings ()
    }
    +enum "<color:red><s>ChannelControl" as ChannelControl <<green>> {
        <color:red><s>KEEP_OPEN
        <color:red><s>CLOSE_AFTER
    }
    +class "<color:red><s><<RuntimeException>>\n<color:red><s>**final** TransactionException" as TransactionException <<green>> {
        +<color:red><s>TransactionException (String message)
        +<color:red><s>TransactionException (String message, Throwable cause)
    }
}

' Associations

' == LAYOUT ==

GenericExtensionService ..> GenericCardSelectionExtension #C_LINK : create >
GenericExtensionService ..> CardTransactionManager #C_LINK : create >

CardTransactionManager ..> ChannelControl #C_USE : use >
CardTransactionManager ..> TransactionException #C_THROW : throw >

' == STYLE ==

package generic #C_GREY1 {}


@enduml